import smtplib

from email.mime.text import MIMEText

from email.mime.multipart import MIMEMultipart





# ==============================

# EMAIL SETTINGS

# ==============================



SENDER_EMAIL = "theakstonjosh@gmail.com"



RECEIVER_EMAIL = "theakston472@icloud.com"



APP_PASSWORD = "xbgfkqoqflndukar"





# ==============================

# SEND EMAIL ALERT

# ==============================



def send_email_alert(signal):



    try:



        subject = (

            "TRADING BOT SIGNAL - "

            + str(signal.get("Direction"))

        )





        body = f"""

LIVE TRADING SIGNAL



Direction:

{signal.get("Direction")}



Entry:

{signal.get("Entry")}



Stop:

{signal.get("Stop")}



Target:

{signal.get("Target")}



Session:

{signal.get("Session")}



Day:

{signal.get("Day")}



Trend:

{signal.get("Trend")}



EMA:

{signal.get("EMA")}



Body Strength:

{signal.get("Body Strength")}



Range:

{signal.get("Range")}





Generated by Trading Bot

"""





        message = MIMEMultipart()



        message["From"] = SENDER_EMAIL

        message["To"] = RECEIVER_EMAIL

        message["Subject"] = subject





        message.attach(

            MIMEText(

                body,

                "plain"

            )

        )





        server = smtplib.SMTP_SSL(

            "smtp.gmail.com",

            465

        )





        server.login(

            SENDER_EMAIL,

            APP_PASSWORD

        )





        server.sendmail(

            SENDER_EMAIL,

            RECEIVER_EMAIL,

            message.as_string()

        )





        server.quit()





        print()

        print("EMAIL ALERT SENT")

        print()





    except Exception as e:



        print()

        print("EMAIL ERROR:")

        print(e)

        print()