"""Legacy email helper using environment-provided credentials only."""

from __future__ import annotations

import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText


def send_email_alert(signal):
    sender = os.environ.get("TRADING_EMAIL_SENDER")
    receiver = os.environ.get("TRADING_EMAIL_RECIPIENT")
    app_password = os.environ.get("TRADING_EMAIL_APP_PASSWORD")
    smtp_host = os.environ.get("TRADING_EMAIL_SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(os.environ.get("TRADING_EMAIL_SMTP_PORT", "465"))
    if not all((sender, receiver, app_password)):
        raise RuntimeError(
            "Email alerts are not configured. Set TRADING_EMAIL_SENDER, "
            "TRADING_EMAIL_RECIPIENT, and TRADING_EMAIL_APP_PASSWORD."
        )

    subject = f"TRADING BOT SIGNAL - {signal.get('Direction')}"
    body = "\n".join(
        [
            "LIVE TRADING SIGNAL",
            "",
            f"Direction: {signal.get('Direction')}",
            f"Entry: {signal.get('Entry')}",
            f"Stop: {signal.get('Stop')}",
            f"Target: {signal.get('Target')}",
            f"Session: {signal.get('Session')}",
            f"Day: {signal.get('Day')}",
            f"Trend: {signal.get('Trend')}",
            f"EMA: {signal.get('EMA')}",
            f"Body Strength: {signal.get('Body Strength')}",
            f"Range: {signal.get('Range')}",
            "",
            "Generated by Trading Bot",
        ]
    )
    message = MIMEMultipart()
    message["From"] = sender
    message["To"] = receiver
    message["Subject"] = subject
    message.attach(MIMEText(body, "plain"))
    with smtplib.SMTP_SSL(smtp_host, smtp_port) as server:
        server.login(sender, app_password)
        server.sendmail(sender, receiver, message.as_string())
